// <auto-generated />
using System;
using MegaDeskRazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MegaDeskRazorPages.Migrations
{
    [DbContext(typeof(MegaDeskRazorPagesContext))]
    partial class MegaDeskRazorPagesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MegaDeskRazorPages.Models.Desk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<int>("area")
                        .HasColumnType("int");

                    b.Property<int>("depth")
                        .HasColumnType("int");

                    b.Property<int>("drawers")
                        .HasColumnType("int");

                    b.Property<int>("width")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Desk");
                });

            modelBuilder.Entity("MegaDeskRazorPages.Models.DeskQuote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int?>("DeskID")
                        .HasColumnType("int");

                    b.Property<string>("DeskMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDrawers")
                        .HasColumnType("int");

                    b.Property<DateTime>("QuoteDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("QuoteTotal")
                        .HasColumnType("float");

                    b.Property<int>("RushDays")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DeskID");

                    b.ToTable("DeskQuote");
                });

            modelBuilder.Entity("MegaDeskRazorPages.Models.DeskQuote", b =>
                {
                    b.HasOne("MegaDeskRazorPages.Models.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskID");

                    b.Navigation("Desk");
                });
#pragma warning restore 612, 618
        }
    }
}
